export { default as AboutHero } from './AboutHero'
export { default as AboutStory } from './AboutStory'
export { default as AboutStats } from './AboutStats'
export { default as AboutValues } from './AboutValues'
export { default as AboutTimeline } from './AboutTimeline'
export { default as AboutTeam } from './AboutTeam'
export { default as AboutCta } from './AboutCta'
