// ── Enums — exact casing as defined in the backend Prisma schema ─────────────
export type Species = 'DOG' | 'CAT' | 'RABBIT' | 'BIRD' | 'OTHER'
export type Gender  = 'MALE' | 'FEMALE'
export type Size    = 'SMALL' | 'MEDIUM' | 'LARGE' | 'EXTRA_LARGE'

// Filter-only values used by the public Browse Pets page (not sent to backend)
export type SpeciesFilter = 'ALL' | Species
export type GenderFilter  = 'ANY' | Gender
export type SizeFilter    = 'ANY' | Size

// ── Display label helpers ─────────────────────────────────────────────────────

export function speciesLabel(s: Species): string {
  const map: Record<Species, string> = { DOG: 'Dog', CAT: 'Cat', RABBIT: 'Rabbit', BIRD: 'Bird', OTHER: 'Other' }
  return map[s]
}

export function genderLabel(g: Gender): string {
  return g === 'MALE' ? 'Male' : 'Female'
}

export function sizeLabel(s: Size): string {
  const map: Record<Size, string> = { SMALL: 'Small', MEDIUM: 'Medium', LARGE: 'Large', EXTRA_LARGE: 'Extra Large' }
  return map[s]
}

export function speciesFilterLabel(s: SpeciesFilter): string {
  return s === 'ALL' ? 'All' : speciesLabel(s)
}

export function genderFilterLabel(g: GenderFilter): string {
  return g === 'ANY' ? 'Any' : genderLabel(g)
}

export function sizeFilterLabel(s: SizeFilter): string {
  return s === 'ANY' ? 'Any' : sizeLabel(s)
}

// ── PetCard ───────────────────────────────────────────────────────────────────
// This is the frontend view model. The backend stores only the core fields;
// the display-only fields (svg, bg, color, traits, etc.) are generated by the
// adapter (apiPetToPetCard) when the backend does not provide them.

export interface PetCard {
  id: number
  name: string
  species: Species
  breed: string
  ageMonths: number
  gender: Gender
  size: Size
  status: 'AVAILABLE' | 'PENDING' | 'ADOPTED'
  shelterId: number
  // Flattened from the shelter relation in API responses:
  shelterName: string
  shelterCity: string
  // Display-only (not stored in backend):
  bg: string
  svg: React.ReactNode
  color: string
  imageUrl?: string
  imageUrls?: string[]
  // Extended info (not in backend — defaulted empty by the adapter):
  description: string
  traits: string[]
  vaccinated: boolean
  neutered: boolean
  houseTrained: boolean
  goodWith: string[]
}

export function ageLabel(months: number): string {
  if (months < 12) return `${months}mo`
  const years = Math.floor(months / 12)
  const rem = months % 12
  return rem > 0 ? `${years}y ${rem}mo` : `${years}y`
}
